version: '3.8'

services:
  qdrant:
    image: qdrant/qdrant
    container_name: qdrant
    ports:
      - "6333:6333"
    volumes:
      - qdrant_data:/qdrant/storage
    networks:
      - cutru-network

  redis:
    image: redis:7
    container_name: redis
    ports:
      - "6379:6379"
    networks:
      - cutru-network

  backend:
    build:
      context: .
      dockerfile: Dockerfile.backend
    container_name: cutru-backend
    ports:
      - "8000:8000"
    environment:
      QDRANT_HOST: qdrant
      QDRANT_PORT: 6333
      REDIS_HOST: redis
      REDIS_PORT: 6379
    depends_on:
      - qdrant
      - redis
    networks:
      - cutru-network

  frontend:
    build:
      context: .
      dockerfile: Dockerfile.frontend
    container_name: cutru-frontend
    ports:
      - "3000:3000"
    depends_on:
      - backend
    networks:
      - cutru-network

  nginx:
    image: nginx:latest
    container_name: cutru-nginx
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - frontend
      - backend
    networks:
      - cutru-network

networks:
  cutru-network:
    driver: bridge

volumes:
  qdrant_data: