claude:
  model_id: "anthropic.claude-3-5-sonnet-20240620-v1:0"
  max_tokens: 1000
  temperature: 0.1
  top_p: 0.99
  top_k: null
  anthopic_version: "bedrock-2023-05-31"
  stop_sequences: null
llama:
  model_id: "us.meta.llama4-scout-17b-instruct-v1:0"
  max_gen_len: 2000
  temperature: 0.5
  top_p: 0.9
  top_k: null
  stop_sequences: null
cache:
  cache_limit: 1000
  chunk_size: 100
  threshold: 0.85
  paraphrase_cache_prefix: "paraphrase_cache:"
  cache_key: "semantic_prompt_cache"
langsmith:
  project_name: "cutru-chatbot"
  api_url: "https://api.smith.langchain.com"
  tracing_enabled: true
  tags:
    - "development"
    - "rag-workflow"
    - "vietnamese-legal"
  metadata:
    application: "cutru-chatbot"
    version: "2.0.0"
    environment: "development"
llm:
  prompt_version: "v1"
  default_model_name: "us.meta.llama4-scout-17b-instruct-v1:0"
embedding:
  model_name: "Alibaba-NLP/gte-multilingual-base"

voice_to_text:
  model_name: "vinai/PhoWhisper-medium"
  batch_size: 8
  num_workers: 1
  device: null # null for auto-detect, 0 for GPU, -1 for CPU
  preload_model: true
  vad_aggressiveness: 3
  frame_duration: 30
  sample_rate: 16000
intent:
  router_system_prompt: |
    Bạn là một trợ lý thông minh có khả năng định tuyến truy vấn người dùng đến MỘT hoặc NHIỀU cơ sở dữ liệu chuyên biệt.
    Hiện có 5 cơ sở dữ liệu mà bạn có thể sử dụng:
    1. **thu_tuc_hanh_chinh**: Truy vấn liên quan đến thủ tục hành chính trong lĩnh vực cư trú như: trình tự, thành phần hồ sơ, cách thực hiện, thời gian xử lý,...
    2. **luat_cu_tru**: Truy vấn liên quan đến văn bản pháp lý, căn cứ pháp lý, điều luật, quy định trong lĩnh vực cư trú.
    3. **giay_to_cu_tru**: Truy vấn liên quan đến cách điền giấy tờ, biểu mẫu, tờ khai, đơn, phiếu đề nghị,... dùng trong lĩnh vực cư trú.
    4. **template_cu_tru**: Truy vấn liên quan đến biểu mẫu, tờ khai, đơn, phiếu đề nghị,... dùng trong lĩnh vực cư trú.
    5. **giao_tiep_chung**: Truy vấn không liên quan đến cư trú, bao gồm các câu hỏi chào hỏi, cảm ơn, hỏi vu vơ, giới thiệu bản thân,... hoặc những nội dung giao tiếp hàng ngày.
    ## Chú ý: 
     - Nếu truy vấn về thủ tục hành chính, hãy trả về cả các cơ sở dữ liệu về quy định pháp lý và biểu mẫu nếu có liên quan.
     - Với mỗi truy vấn, hãy liệt kê đầy đủ tất cả các tool phù hợp (không loại trừ lẫn nhau).
     - Khi câu truy vấn liên quan đến các trường hợp hay tình huống cụ thể thì truy vấn liên quan đến văn bản pháp lý
     - Các câu truy vấn liên quan đến hai cơ sở dữ liệu khác nhau thì nên trả về 2 cơ sở dữ liệu

  intent_to_collections:
    procedure: [procedure]
    law: [legal]
    form: [procedure]
    term: [legal]
    template: [procedure]
    general: [general]

prompt_templates:
  base_template: |
    Bạn là chuyên gia pháp lý về pháp luật hành chính và cư trú tại Việt Nam.

    NGUYÊN TẮC TRẢ LỜI:
    - Trả lời NGẮN GỌN, TẬP TRUNG vào câu hỏi cụ thể
    - Chỉ dùng thông tin từ phần THÔNG TIN THAM KHẢO. Không suy đoán ngoài phạm vi
    - Ưu tiên thông tin QUAN TRỌNG NHẤT và TRỰC TIẾP NHẤT với câu hỏi
    - Tránh lặp lại thông tin không cần thiết
    - Khi trích dẫn luật: chỉ nêu điểm chính, tránh copy nguyên văn dài dòng
    - Cấu trúc: TRỰC TIẾP trả lời câu hỏi → Nêu căn cứ pháp lý chính → Kết luận ngắn gọn

    THÔNG TIN THAM KHẢO:
    {context}

    CÂU HỎI: {question}

    TRẢ LỜI (ngắn gọn, tập trung):
